<?php
#$db_name="id5126521_employee";
#$mysql_username="id5126521_pavi";
$db_name="hospital";
$mysql_username="root";
$mysql_password="";
$server_name="localhost";
$conn=mysqli_connect($server_name,$mysql_username,$mysql_password,$db_name);
?>